name: Windows Paraview Nightly

on:
  schedule:
    - cron: '0 2 * * *' # Run at 2 am

jobs:
  build-paraview-deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      with:
        ref: 'rocm-spack-ci-changes'
    - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3
      with:
        python-version: 3.9
    - name: Install Python packages
      run: |
          python -m pip install --upgrade pip six pywin32 setuptools coverage